dist: trusty
language: cpp
addons:
    apt:
        sources:
            #- llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            #- clang-3.7
            - g++-5
            - gcc-5
            - build-essential
            - libcrypto++-dev
            - libcurl4-openssl-dev
            - libpoco-dev
            - libssl-dev
            - uuid-dev
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  # Grab a version of CMake >= 3.4
  - wget --no-check-certificate https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.sh
  - chmod a+x cmake-3.5.2-Linux-x86_64.sh
  - sudo ./cmake-3.5.2-Linux-x86_64.sh --skip-license --prefix=/usr/local

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make install
  - cd ../examples/standaloneclient
  - mkdir build
  - cd build
  - cmake ..
  - make
